services:
  carte:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8092:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./2-css:/usr/share/nginx/html/2-css:ro
      - ./3-js:/usr/share/nginx/html/3-js:ro
      - ./data:/usr/share/nginx/html/data:ro
      - ./fiches:/usr/share/nginx/html/fiches:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
